import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from 'react';
import { Poppins } from 'next/font/google';
import Header from "./Component/Header";
import Footer from "./Component/Footer";
import { CartProvider } from "@/app/Component/CreateContext";

const poppins = Poppins({
  subsets: ['latin'], // Add other subsets if needed
  weight: ['400','500', '600', '700'], // Specify font weights
  variable: '--font-poppins', // Custom CSS variable
});


export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app and Tailwind CSS",
  icons: {
    icon: "/favicon.png",
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={poppins.className}>
      <Suspense fallback={<div>Loading...</div>}>
        <CartProvider>
        <Header />
          {children}
        </CartProvider>   
        </Suspense>  
           <Footer />
        </body>
    </html>
  );
}
